import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar"
import Footer from "./Components/Footer";

import { ClerkProvider } from '@clerk/nextjs'
// import { AppRouterCacheProvider } from '@mui/material-nextjs/v1X-appRouter'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
 
    <html lang="en">
      <body className={inter.className}>
    
        <Navbar />
       
        {children}
        <Footer />
    
        </body>
    </html>
       </ClerkProvider>
  );
}